version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'user_pg'
      POSTGRES_PASSWORD: 'user_pg'
    volumes:
      - '.db-data/:/var/lib/postgresql/data/'